/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "proto/vridge-api.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Beacon, Beacon, AUTO)


PB_BIND(ControllerStateRequest, ControllerStateRequest, 2)


PB_BIND(ControllerStateResponse, ControllerStateResponse, AUTO)


PB_BIND(HapticPulse, HapticPulse, AUTO)


PB_BIND(HeadTrackingRequest, HeadTrackingRequest, AUTO)


PB_BIND(HeadTrackingResponse, HeadTrackingResponse, AUTO)


PB_BIND(TrackedPose, TrackedPose, AUTO)


PB_BIND(VRController, VRController, 2)


PB_BIND(VRControllerAxis_t, VRControllerAxis_t, AUTO)


PB_BIND(VRControllerState_t, VRControllerState_t, AUTO)






/* On some platforms (such as AVR), double is really float.
 * Using double on these platforms is not directly supported
 * by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
